- name: docker | install packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ development_docker_package_list }}"

- name: docker | add user to docker group
  become: true
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: docker | start service
  become: true
  ansible.builtin.systemd_service:
    name: docker 
    enabled: true
    masked: no

- name: docker | enable service
  become: true
  ansible.builtin.systemd_service:
    name: docker 
    state: started 
