- name: install shell packages 
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_shell_package_list }}"

# - name: change default shell to zsh
#   shell: chsh -s /bin/zsh jonas
