- name: update system
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: install utility packages 
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_utilities_package_list }}"
