- name: bluetooth | install packages 
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_bluetooth_package_list }}"

- name: bluetooth | start service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    masked: no

- name: bluetooth | enable service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    state: started 
