- name: install bluetooth packages 
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_bluetooth_package_list }}"

- name: enable bluetooth service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    masked: no

- name: start bluetooth service
  become: true
  ansible.builtin.systemd_service:
    name: bluetooth
    state: started 
