- name: install shell packages 
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_shell_package_list }}"

- name: change default shell to zsh for "{{ username }}"
  become: true
  shell: chsh -s /usr/bin/zsh {{ username }}

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
